# fly.toml app configuration file generated for stayfit-client on 2023-08-29T17:16:40-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stayfit-client"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
